@host = http://127.0.0.1:8081/api/v1/users_cart
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEsImV4cCI6MTY1NTI2ODk5Mn0.E8dBiUIN_eK2SWnxus_fU_0gL-DzSo9yeqVRgg3_y3Y
####
GET http://127.0.0.1:8081/api/v1/login HTTP/1.1

### POST
POST http://127.0.0.1:8081/api/v1/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### Get all records by user_id
DELETE http://127.0.0.1:8081/api/v1/users_cart/4?token={{token}} HTTP/1.1
# GET http://127.0.0.1:8081/api/v1/users_cart/7?fields=&offset=0&limit=4&token={{token}} HTTP/1.1

### Get all records by user_id
GET {{host}}/7?token={{token}} HTTP/1.1

### Create new users_cart
POST {{host}}/?token={{token}} HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "user_id": 1,
    "item_id": 14
}

### Create new users_cart
POST {{host}}/?token={{token}} HTTP/1.1
Content-Type: application/json

[

    {
    "id": 1,
    "user_id": 4,
    "item_id": 3
    },
    {
    "id": 2,
    "user_id": 3,
    "item_id": 4
    },
    {
    "id": 3,
    "user_id": 3,
    "item_id": 5
    },
    {
    "id": 4,
    "user_id": 3,
    "item_id": 6
    },
    {
    "id": 5,
    "user_id": 3,
    "item_id": 7
    },
    {
    "id": 6,
    "user_id": 3,
    "item_id": 8
    },
    {
    "id": 7,
    "user_id": 3,
    "item_id": 9
    },
    {
    "id": 8,
    "user_id": 3,
    "item_id": 10
    },
    {
    "id": 9,
    "user_id": 3,
    "item_id": 11
    }
]

### Update users_cart
PUT {{host}}/?token={{token}} HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "name": "Toothpaste",
    "quantity": 5,
    "price": 9.5
}


### Delete users_cart
DELETE {{host}}/?token={{token}} HTTP/1.1
Content-Type: application/json

[3]



### Update sing item
PUT {{host}}/4?token={{token}} HTTP/1.1
Content-Type: application/json

{
  "id": 3, 
  "name": "Whitie"
}


### Delete single user_cart
DELETE {{host}}/3?token={{token}} HTTP/1.1
