@host = http://127.0.0.1:8080/v1/items
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEsImV4cCI6MTY1NDk2MjkwMH0.ogwUSeDnJIugf0t99HkFRdub5fBLcBtd_3uTmFQ2DEA
####
GET http://127.0.0.1:8080/v1/login HTTP/1.1

### POST
POST http://127.0.0.1:8080/v1/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### Get all items
GET {{host}}/?token={{token}} HTTP/1.1

### Get v2
GET {{host}}/?fields=&offset=0&limit=2&token={{token}} HTTP/1.1

### Create new items
POST {{host}}/?token={{token}} HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "name": "Shampoo",
    "quantity": 90,
    "price": 15.50
}


### Create new items
POST {{host}}/?token={{token}} HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "name": "Soap",
    "quantity": 15,
    "price": 10.50
}

### Create new items
POST {{host}}/?token={{token}} HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "name": "Pen",
    "quantity": 30,
    "price": 8.50
}

### Create new items
POST {{host}}/?token={{token}} HTTP/1.1
Content-Type: application/json

[{
    "id": 0,
    "name": "Pencil",
    "quantity": 30,
    "price": 8.50
},
{
    "id": 0,
    "name": "Cup",
    "quantity": 30,
    "price": 8.50
},
{
    "id": 0,
    "name": "Yellow Pad",
    "quantity": 30,
    "price": 8.50
},
{
    "id": 0,
    "name": "Intermediate Pad",
    "quantity": 30,
    "price": 8.50
},
{
    "id": 0,
    "name": "Eraser",
    "quantity": 30,
    "price": 8.50
},
{
    "id": 0,
    "name": "Charger",
    "quantity": 30,
    "price": 8.50
},
{
    "id": 0,
    "name": "Earphones",
    "quantity": 30,
    "price": 8.50
},
{
    "id": 0,
    "name": "Scissors",
    "quantity": 30,
    "price": 8.50
},
{
    "id": 0,
    "name": "Wallet",
    "quantity": 30,
    "price": 8.50
},
{
    "id": 0,
    "name": "Notebook",
    "quantity": 30,
    "price": 8.50
}
]

### Update items
PUT {{host}}/?token={{token}} HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "name": "Toothpaste",
    "quantity": 5,
    "price": 9.5
}


### Delete items
DELETE {{host}}/?token={{token}} HTTP/1.1
Content-Type: application/json

[2, 1]



### Get single item
GET {{host}}/3?token={{token}} HTTP/1.1


### Update sing item
PUT {{host}}/3?token={{token}} HTTP/1.1
Content-Type: application/json

{
  "id": 3, 
  "name": "Whitie"
}


### Delete single item
DELETE {{host}}/10?token={{token}} HTTP/1.1
