@host = http://127.0.0.1:8081/api/v1/users
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEsImV4cCI6MTY1NTIwMDI0Mn0.ZyO9v0O8oKijXGDrX5YMFVr2snfzYSVd_2lL8roQlPE
####
GET http://127.0.0.1:8081/api/v1/login HTTP/1.1

### POST
POST http://127.0.0.1:8081/api/v1/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### Get all users
GET {{host}}/?token={{token}} HTTP/1.1


### Create new users
POST {{host}}/?token={{token}} HTTP/1.1
Content-Type: application/json

[
  {
    "id": 0,
    "fname": "mini",
    "lname": "winie",
    "username": "mini",
    "password": "awww",
    "type": "standard"
  },
  {
     "id": 0,
    "fname": "mini",
    "lname": "koni",
    "username": "minie",
    "password": "awwwzzz",
    "type": "admin"
}
]


### Update users
PUT {{host}}/?token={{token}} HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "username": "mingming4",
    "password": "awww",
    "type": "admin"
}


### Delete users
DELETE {{host}}/?token={{token}} HTTP/1.1
Content-Type: application/json

5



### Get single user
GET {{host}}/2?token={{token}} HTTP/1.1


### Update sing dog
PUT {{host}}/2?token={{token}} HTTP/1.1
Content-Type: application/json

{
  "id": 0, 
  "username": "Whitish"
}


### Delete single dog
DELETE {{host}}/2?token={{token}} HTTP/1.1
